# Generated by Django 3.2.10 on 2021-12-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=200, verbose_name=''),
            preserve_default=False,
        ),
    ]
