# Generated by Django 3.2.10 on 2022-01-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.CharField(max_length=120, verbose_name=''),
        ),
    ]
